### ISSUE TITLE
music - play the hole album

### ISSUE THREAD

**Issue by edch1041** [CommandFusion/XBMC#10]
hello,

when i go to music --> album xxx --> i see all tracks from the album but i cant play all....when i tab track1 track1 starts to play...when i tab play next (on top of the menu) track1 stops and nothing happens. when i tab track2, track2 starts to play. the only way to play the hole album is to tab all playlistbuttons (beside the tracks)...change to playlist and start the tracks from there. would be cool to add the hole album whith one tab to the playlist....maybe i didn't see the button...does anyone know?

regards
c

**Comment by CF-Terence** [comment]
Currently you can only play the tracks one by one by tapping on the item in
the list. Ability to play the whole album is in progress. 

-----Original Message-----
From: edch1041
[mailto:reply+i-2207643-c7a85b9f217c1068f1b9c9ffa9e0c8d50d84a949@reply.githu
b.com] 
Sent: 11 November 2011 17:15
To: CF-Terence
Subject: [XBMC] music play the hole album (#10)

hello,

when i go to music --> album xxx --> i see all tracks from the album but i
cant play all....when i tab track1 track1 starts to play...when i tab play
next (on top of the menu) track1 stops and nothing happens. when i tab
track2, track2 starts to play. the only way to play the hole album is to tab
all playlistbuttons (beside the tracks)...change to playlist and start the
tracks from there. would be cool to add the hole album whith one tab to the
playlist....maybe i didn't see the button...does anyone know?

regards
c

---

Reply to this email directly or view it on GitHub:
https://github.com/CommandFusion/XBMC/issues/10

**Comment by CF-Terence** [comment]
Released on commit 9bd2c0c

**Comment by edch1041** [comment]
tested it already...works fine!
