### ISSUE TITLE
music playlist

### ISSUE THREAD

**Issue by edch1041** [CommandFusion/XBMC#11]
hello,

once again...i created two music playlists --> where can i choose this lists to play. in the menu playlist i only see the actual playqueue but not my two playlists?

regards
c

**Comment by CF-Terence** [comment]
Currently you can only see the play queue. Choosing playlists will be on the
to-do list. 

-----Original Message-----
From: edch1041
[mailto:reply+i-2207674-70c980a35d800de1ba130c1e501e6572e54feaff@reply.githu
b.com] 
Sent: 11 November 2011 17:20
To: CF-Terence
Subject: [XBMC] music playlist (#11)

hello,

once again...i created two music playlists --> where can i choose this lists
to play. in the menu playlist i only see the actual playqueue but not my two
playlists?

regards
c

---

Reply to this email directly or view it on GitHub:
https://github.com/CommandFusion/XBMC/issues/11
