### ISSUE TITLE
no connection with XBMC-8051c3e plugin

### ISSUE THREAD

**Issue by edch1041** [CommandFusion/XBMC#12]
hello,

i'm using a mac mini with xbmc pre-11.0 git:2011113-993e6d2.

today i tried the new CF macro 8051c3e but i can't get a connection...when
i changed to the old macro b3913e0 it worked....same settings everthing ident.

witch version of xbmc do you use for the new macro?

ce

**Comment by CF-Terence** [comment]
Using the same XBMC version (Oct 26 as per markdown file) and tested with two different XBMC machines - both are working. I've also downloaded the latest nightlies 16 Nov (XBMCSetup-20111116-57ba0cb-master.exe) and tested - it's working fine. Can you post your debugging log or the error msg that you're getting? Make sure the license that you're entering is the correct one.

**Comment by edch1041** [comment]
following log is reported:

> Javascript interface up and running, opening connection with iViewer
> Established connection with iViewer
> iViewer version: v4.0.5 build 171
> Start running user code
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> System name: HTPC
> Host name/IP address: 192.168.100.82
> Port: 8080
> Username: xbmc
> Password: xbmc
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> System name: HTPC
> Host name/IP address: 192.168.100.82
> Port: 8080
> Username: xbmc
> Password: xbmc
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode
> Can't make HTTP requests in Lite mode

**Comment by CF-Terence** [comment]
Please delete the current licensing details in the project and re-enter your license again. Please also make sure that you have the latest iViewer4/Next installed. 
You can read through this topic also for more info for a similar issue :
https://github.com/CommandFusion/XBMC/issues/7

**Comment by edch1041** [comment]
damn, forgot the license....working fine! thanks

**Comment by CF-Terence** [comment]
You're welcome! :)
