### ISSUE TITLE
Problem Connecting

### ISSUE THREAD

**Issue by nicosquare** [CommandFusion/XBMC#13]
Hi CF Team,

I'm having problems with connection with XBMC. I really don't know why it isn't working, but the debugger indicates:

> Exception caught while processing response in xbmc.rpc: TypeError: 'null' is not an object (evaluating 'data.result.limits')
> Exception caught while processing response in xbmc.rpc: TypeError: 'undefined' is not an object (evaluating 'data.result.limits.total')
> Exception caught while processing response in xbmc.rpc: TypeError: 'undefined' is not an object (evaluating 'data.result.limits.total')
> ERROR REPLY ---------
> code = -32601
> message = Method not found.

Could anybody help me, thanks a lot.

Regards.

**Comment by CF-Terence** [comment]
Are you using the latest nightlies? I'vejust  tested with the most recent (16 Nov) and it's working. Please try it out.
