### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by gbibi** [CommandFusion/XBMC#14]
Hi CF Support
   I've installed :
- XBMC 20111116-57ba0cb (win 32 on my win Xp pc);
- Iviewer v3.4.2 build 124 on my Ipad;
- Ipad license is ok (I see page flip etc.. so I think thats ok);
  I've configured:
- on Edit -> Project Properties -> Global Token the IP/Port and xbmc password;
  I've loaded latest GUI (1 day ago).
  My problem:
  On Ipad:
- I don't see popup for remote debug IP over browser;
- I don't see in Setting the IP configuration like Global Token (the setting are blank);
  so I don't see nothing (no connection or debug )

**Comment by CF-Terence** [comment]
Hi please download and use iViewer 4 from the App Store. Version 3..4.2 is outdated and won't have most of the latest features.

**Comment by gbibi** [comment]
Many Thanks Terence .
Now work fine!! :-)

**Comment by CF-Terence** [comment]
You're welcome! :)
