### ISSUE TITLE
Movie's List 

### ISSUE THREAD

**Issue by efremov476** [CommandFusion/XBMC#15]
Hi,

I don't know if you get same problem that me but when when i start iviewer and go to Movie's Tab, I can see the list and when i click on second one or third he gives me the detail from 1 st movie.

I must go until the end of the movie's list and everything will be ok.

Sorry for my english

Im using nightly

**Comment by efremov476** [comment]
with Iviewer 4 no problem, work perfectly for this part.

with Iviewer Next b190 nop

**Comment by CF-Terence** [comment]
Please use Iviewer 4 onwards. Any other previous versions will not have all the latest features and won't be up to date.

**Comment by efremov476** [comment]
Oh sorry was thinking that 4.0.190 was lastest.
