### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Theiamania** [CommandFusion/XBMC#17]
Hello Jarrod and Terence, thanks for all.

First let me apologize for my bad English.

Surely you know the current failures of this gui , but I made a list of the bug's I've found on Win7 with lasted versions of gui and XBMC nightly:
- When I press on some Movie item in "recently added" list in Home page nothing happens, although if you can play music from this page.
- Accents are not correctly in Playing Page or in the information that appears in the Movie Page, but if you look at the synopsis
- Unable to play files from Files Page
- In Movies Page, clicking on a movie item unless you select the film down but the previous one, except the first and the last of the list. This error occurs to change the configuration of the gear button.

I conclude with a question: How can I play the playlist stored on XBMC?

Best regards.
Roy

**Comment by CF-Terence** [comment]
Hi there Roy, thanks for the feedback and here's the reply for the questions.
- Play Recent Movie on the front page : Fixed and will be in the next commit, will be released soon.
- Accents on the Playing Now Page : Fixed
- Playing files from Files age : On the to-do list.
- About the Movis Page: Don't really understand this part. Can you give an example?
- Play the playlist stored : On the to-do list.

By the way, which version of iViewer are you using?

**Comment by Theiamania** [comment]
Thank you Terence!

My viewer is iViewer Next v4.0.190 build 190

Regards

**Comment by CF-Terence** [comment]
Item 1 and 2 updated and released on commit 9bd2c0c840.

**Comment by Theiamania** [comment]
Downloading and checking ;-)

**Comment by CF-Terence** [comment]
Item 3 - Play files from File Page updated on commit ed5c54621b (developmental branch). To play the file, hold down the button for more than 1s.
