### ISSUE TITLE
autoupdate of movie list

### ISSUE THREAD

**Issue by nouveaudepart** [CommandFusion/XBMC#18]
It just added some movie on my nas, and it seems that the movie list doesn't update until i completely close iviwer and restart.
could a timer be included so that it refreshes the movie (and album) list?

**Comment by CF-Terence** [comment]
Having a timer to refresh won't be too practical if you have a large amount of movies and albums as it'll need to constantly clears the global data array and reloads the list again and it takes some time to load all the lists. 

The solution is actually very simple : Go to the Main Page -> Settings Drop Down menu -> IP Address (no need to change anything) -> Once the keyboard pops up -> Press "Done" again, it'll refresh the current data.

In the todo list - is to add a Refresh button in the Settings drop down menu. Next time just pressing that button will refresh the data to the latest.

**Comment by nouveaudepart** [comment]
thanks for the info
