### ISSUE TITLE
View Menu in Music Menu

### ISSUE THREAD

**Issue by efremov476** [CommandFusion/XBMC#2]
If I click in ablum View menu for music by exemple, i can see only album from last chose artist, not from my complete list, same for songs

**Comment by CF-Terence** [comment]
This is the correct and how it should work for the current beta version. Viewing all albums and all songs is on the to-do list and is in progress.

**Comment by CF-Terence** [comment]
Additions updated in the latest commit 5f40185. Please go to the developemental branch to get the latest codes.
