### ISSUE TITLE
album view to add (audio)

### ISSUE THREAD

**Issue by nouveaudepart** [CommandFusion/XBMC#20]
it seems there is no album view, only by artist or album by artist.
It could be nice like in itunes to have an album view.

**Comment by CF-Terence** [comment]
The script and GUI has been done actually for All Albums and All Songs. Currently still running some tests on it and once it's done, will be updated to the Github.

**Comment by nouveaudepart** [comment]
thank you

**Comment by CF-Terence** [comment]
Additions updated in the latest commit 5f40185cb2. Please go to the developemental branch to get the latest codes.
