### ISSUE TITLE
Problem with Latset nightly?

### ISSUE THREAD

**Issue by nouveaudepart** [CommandFusion/XBMC#21]
Terrence,

Have you tried the lastest nightly?
i tried yesterday but had some problems, not sure it the plugin, or something wit my gui.
I wodl like to have your feedback, i'm currently on 19/11 nightly and all works

**Comment by CF-Terence** [comment]
Hi there.. just downloaded the latest one (29 Nov) and also one in Nov (16 Nov) and both works fine on 2 test machines. The usual debugging methods - check your licensing and test connectivity with Google Chrome Simple Rest Client (can refer to markdown file if you're not familiar with it).

Also, can you let me know what error message that you're getting on the debugger?

**Comment by nouveaudepart** [comment]
Terence,

sorry, it works just tried the latesd nightly, and everything is ok.
