### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by sjgough** [CommandFusion/XBMC#22]
Terrence,
 I am having issues connecting my IPad 2 running Iviewer v4.0.194 build 194 to my xbmc machine. I have double checked the IP address, the ports and also the username and password. I have even tried using the nightly build from November 26th to see if that is the issue. I can send commands using the google chrome simple rest client with no problem. I just loaded the lastest nightly build from December 10th and still can not connect. 
 Do i have to install some kind of addon onto my xbmc machine ? 
 Thanks in advance 
 Steve

**Comment by CF-Terence** [comment]
You won't have to add any addons. Did you load your license? And try to run through the checklists that it's written in the markdown file. We've tested and ran with the latest nightly builds (early Dec) and all are working fine.

**Comment by sjgough** [comment]
I have read through the markdown file and tried different ports to connect to xbmc, i have tried connecting on 2 different PC's running XBMC with no luck. I have downloaded the xbmc commander app from Itunes and i can connect with this so i know my IP and port settings are correct.

**Comment by zobi** [comment]
Are you using the good version of XBMC : XBMC Nightly ?

**Comment by sjgough** [comment]
Yes, I have downloaded the latest nightly. I have tried several versions of the nightlies but with no success.

**Comment by CF-Terence** [comment]
Can you post what error message that the debugging log is showing?

**Comment by sjgough** [comment]
Do you mean the debug log from the Ipad or the one from XBMC ?

**Comment by CF-Terence** [comment]
The iViewer's debugger - read this link on how to set it up: http://www.commandfusion.com/docs/scripting/debug.html

**Comment by sjgough** [comment]
Thanks for your patience, i was having a stupid moment and using my device ID instead of the registration code. As soon as i ran the debugger i saw it was the lite version. Sorry for being so stupid and bothering you.
