### ISSUE TITLE
PSD Photoshop or filter

### ISSUE THREAD

**Issue by zobi** [CommandFusion/XBMC#23]
Hi, thanks for this XBMC Project, is it possible to share the psd file to create the png like "menu_music_on.png" ?
It's for make traduction ;)

Thanks a lot

**Comment by CF-Terence** [comment]
Will upload it to the github soon. Need to do some cleanup first.

**Comment by zobi** [comment]
Thanks a lot Terence ;)

**Comment by CF-Terence** [comment]
The design file is already uploaded. You can get it from the PSD folder.

**Comment by zobi** [comment]
Thank you very much ;)

**Comment by CF-Terence** [comment]
You're welcome :)
