### ISSUE TITLE
Context menu button en menu button

### ISSUE THREAD

**Issue by nouveaudepart** [CommandFusion/XBMC#24]
Terrence,

Is there any plan to have acces to te same commands as on the original appel tv remote?
the arrows, ok, play-pause button are already there but others are missing and are quite usefull:

I mean:
- the context menu (when you long press on OK button) gives acces to the subtiltles and audio options
- Menu button , to exit the context menu.

thank you

**Comment by CF-Terence** [comment]
It'll depends very much on whether the current JSON implementation supports it. The latest doesn't have this features but you can toggle on/off the subtitles with the latest JSON version :

{"jsonrpc": "2.0", "method": "Player.SetSubtitle", "params": {"playerid": 1, "subtitle" : "on"}, "id": "1"}
{"jsonrpc": "2.0", "method": "Player.SetSubtitle", "params": {"playerid": 1, "subtitle" : "off"}, "id": "1"}

**Comment by nouveaudepart** [comment]
is there any other way to have access to this menu?

Because it is not just to turn the subs on or off, but also chose the file for the subs and sometimes ajust the delay and other stuf,....
