### ISSUE TITLE
File name 

### ISSUE THREAD

**Issue by Theiamania** [CommandFusion/XBMC#25]
Hello Terence.
I'm using your XBMC gui in a meeting room gui.

I need file name showed in Playing page. I don't need "Artist", "Year"... just only file name.

How can I do it? 
In this place we play only non commercial a/v files. Never movies or music. 
I need know what file are current playing.

Thank you

**Comment by CF-Terence** [comment]
You can add another item to the properties of the Player.GetItem method - "file". This will give you back the file name and the full path of the file.

You can look at the JS in the "File" page in the module on how this is used.

**Comment by Theiamania** [comment]
Thank you Terence.

But I don't know Javascript. I use CF to control ASPEN audio matrix, and XBMC is something new for me.

Please, send me js file or say me step by step what I need to do.

Best regards
Roy

**Comment by CF-Terence** [comment]
Drop me your email and GUI file at terence@commandfusion.com

**Comment by CF-Terence** [comment]
Done.
