### ISSUE TITLE
Parsing Streamdetails

### ISSUE THREAD

**Issue by ghost** [CommandFusion/XBMC#27]
Hi !

I try to parse streamdetails (codec, language etc..) in the VideoLibrary.GetMovieDetails command. I add this variable for codec.

var codec= data.result.moviedetails.streamdetails.video.codec;
CF.log("Resultat du test: " + codec); 

I have this result

Resultat du test: undefined

with CF.logObject(data); I have this log

....runtime = 88
....streamdetails: {
......audio: {
........0 = object (increase log depth to see contents)
........1 = object (increase log depth to see contents)
......}
......subtitle: {
........0 = object (increase log depth to see contents)
......}
......video: {
........0 = object (increase log depth to see contents)
......}
....}
....thumbnail = special://masterprofile/profiles/ADULTE/Thumbnails/Video/c/cc03f1fa.tbn
....title = Ados vs extraterrestres (Fr,En)

Is it possible to parse streamdetails ?

Thanks
Steven

**Comment by CF-Terence** [comment]
The log shows that the variable codec is undefined. 

My sample reply is :
{"id":1,"jsonrpc":"2.0","result":{"moviedetails":{"label":"Alice in Wonderland","movieid":1,"streamdetails":{"audio":[{"channels":2,"codec":"mp3","language":""}],"video":[{"aspect":1.8095240592956543,"codec":"dx50","duration":6517,"height":336,"width":608}]}}}}

Checking through your declaration for the variable seems ok but I hope this is a typo error though :

var codec= data.result.moviedetails.streamdetails.video.codec;

or else you'll need a space after the var codec.

**Comment by ghost** [comment]
I put a space after var codec with no result. How I can increase log depth to see object in the log.

**Comment by ghost** [comment]
I check in this tool Json Parser Online. audio and video it's an array. Maybe it's the problem.

**Comment by ghost** [comment]
I found the problem and parse perfectly.

**Comment by CF-Terence** [comment]
That's great!

**Comment by ghost** [comment]
Terence

I would like to thank you for your XBMC plugin. Good job. I did not know javascript but I learned a lot with your module.

Thanks
Steven

**Comment by CF-Terence** [comment]
You're welcome! :) Thanks for your support to CF as well.
