### ISSUE TITLE
Cannot play audio files

### ISSUE THREAD

**Issue by xbmc4ever** [CommandFusion/XBMC#29]
I am able to connect to my XBMC instance (V12.1) but I could not play any audio files, video works fine.
When I select “Music” in the menu I can see the artists, when I select “Albums” via the Options I see the album but that’s it. A click on an artist does not show his albums, a click on an album does not show its titles.
And if I click on play at “Play Album” nothing happens.
I tried some XBMC-Control apps on the iPad like XBMC Remote and there everything works so I assume that the ID3-Tags of my Files are correct.

Thanks for help!
Phil

**Comment by CF-Terence** [comment]
Can you list down for me your system setup? IOS version, ipad generation, etc. Some of the features have yet to be updated for Frodo so you might encounter this problem.

**Comment by xbmc4ever** [comment]
That's on an iPad1, iOS 5.1.1. Following your answer I tried it with an older XBMC (11.0) where it works. So it might be Frodo ... When is an updated version planned for release?
Many thanks,
Phil

**Comment by CF-Terence** [comment]
Just released a new commit to fix the Audio Library navigation and file playing. Tested with iPad1 (exactly same setup like yours) and ipad4 and both are working fine. Let me know if those are not working.

**Comment by xbmc4ever** [comment]
Hi Terence,
I just tested it but could not connect to any XBMC instance. The wifi-led also stayed red. Thereafter I tried with the previous version, there I got connected. Settings are the same (Device has been registered and global token settings entered.) Anything else to be set in the new version?
Regards, Phil

**Comment by CF-Terence** [comment]
Did you see the System Disconnected Page? Else try to remove your device license and re-enter again. Make sure your global token settings is directing to your XBMC system's IP.

**Comment by xbmc4ever** [comment]
Got it running know: I just took the xbmcapp.js from the new version, all other files from the previous one and now it works. Maybe some files were damaged during download or extract, don't know ...
Many thanks for the quick solution!
Phil

**Comment by CF-Terence** [comment]
You're welcome ... good to hear that all is well. Cheers!

**Comment by xbmc4ever** [comment]
No, I never saw the System Disconnected page. Obviously the app never got any connection, but WLAN was OK (used it for the Upload Service). But it works now ...
