### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by efremov476** [CommandFusion/XBMC#4]
Can't change song in playlist with button on top in playlist tab

**Comment by CF-Terence** [comment]
There's no button to enable song changes in the Playlist section, only can to play, delete or refresh the file or playlist. Which button are you referring to?

**Comment by efremov476** [comment]
by exemple next or previous music in playlist

**Comment by CF-Terence** [comment]
I believe the buttons that you are referring to are on the top menu bar on the left corner (rewind/play/forward button). These buttons are not used for playlist operations but it's for video/audio player operation.
