### ISSUE TITLE
Cannot play media from "File" tab

### ISSUE THREAD

**Issue by ZikiBe** [CommandFusion/XBMC#5]
I have this error in the debugger:

> ERROR REPLY ---------
> code =   -32602
> message =   Invalid params.

json request is : {"jsonrpc":"2.0","method":"Files.GetDirectory","params":{"directory":"D:\Mp3\Natalie Imbruglia - Shiver.Mp3"},"id":832}

I think that it's not the correct method.

**Comment by CF-Terence** [comment]
Currently the feature for playing media from the File tab is not implemented yet. You can only browse through the directory to see the list of files and folders.

**Comment by CF-Terence** [comment]
Play files from File Page updated on commit ed5c546 (developmental branch). To play the file, hold down the button for more than 1s.

**Comment by Theiamania** [comment]
Hello Terence.

I try play files from File Page with last versions of XBMC night, iViewer 4 and iViewer Next, but I press button down and do nothing. I'm doing something wrong?

**Comment by CF-Terence** [comment]
Try again with the latest commit b58716e31b. Some how the updates were not updated previously when pushed - the latest have some other updates as well.
