### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by vaclavgreif** [CommandFusion/XBMC#7]
I tested it on multiple machines, running different versions of XMBC, somehow I'm not able to connect. The web interface remote works fine though, so I think my settings are correct...

**Comment by vaclavgreif** [comment]
The message I get in debug is: Can't make HTTP request in Lite mode...

**Comment by CF-Terence** [comment]
Did you enter the license for your project? Also make sure you're using the latest nightlies, there's been some recent major protocol changes recently.

**Comment by vaclavgreif** [comment]
I imported the devices from my other project into Manage Devices - is this a correct way? I tried latest nightly, and also the one you suggested..

**Comment by CF-Terence** [comment]
You can't directly import the devices from the other project unless the you're using the same device. Different devices will have different device ID, you'll need to enter the correct license for the device you're using.

**Comment by vaclavgreif** [comment]
Yes, I use the same device as with my own project - I uploaded your gui just for testing reasons. Is there any way to check if the license is assigned correctly?

**Comment by CF-Terence** [comment]
Please delete the current device settings and re-enter your device settings again.

**Comment by vaclavgreif** [comment]
I did that already, no luck. I think I have license key correctly, as in the case it would be wrong, page flips won't work, right? I use iViewer Next, the Gui displays fine, switching between pages works, but no content is loaded...

**Comment by CF-Terence** [comment]
Try to restart the app again. Which version of iViewer Next are you using?

**Comment by vaclavgreif** [comment]
Thanks for suggestions. I downloaded iViewer4, which works fine! So this is maybe some iViewer Next problem?

**Comment by CF-Terence** [comment]
Just make sure you use the latest iViewer Next. It's running fine on my Iviewer Next v4.0.184 and iViewer 4 as well.
