### ISSUE TITLE
Global Token

### ISSUE THREAD

**Issue by foneworkshop** [CommandFusion/XBMC#8]
Set the Global token as per instructions but it does not show movie lists etc when connecting. If I then go into the settings and put in the IP/port etc it does? Using same details

Cheers

**Comment by CF-Terence** [comment]
Either way should work ... are you using the latest nightlies version of the XBMC?

**Comment by foneworkshop** [comment]
Hi terence,

Yes I used the last nightly 31/10. Just wondering, As the XBMC demo GUi was a lot larger than my existing one, I copied everything of mine into it.Everything else works fine, just won't connect until I manually alter port etc

Cheers

**Comment by CF-Terence** [comment]
You should be able to see your new settings once you had altered the Global Tokens when you've just uploaded your GUI (before you manually alter the IP settings, etc.) How are you changing the value of the Global Tokens? You should be doing it via Edit-> Project Properties -> Global Token Manager

**Comment by foneworkshop** [comment]
Hi Terence,

Do it the way you say, when I reload the GUI to G/D it shows they are there
and correct,  Haven't checked after upload, can you view them on ipad before
manually altering?

Cheers

-------Original Message-------

From: CF-Terence

Date: 11/07/11 12:39:27

To: foneworkshop

Subject: Re: [XBMC] Global Token (#8)

You should be able to see your new settings once you had altered the Global
Tokens when you've just uploaded your GUI (before you manually alter the IP
settings, etc.) How are you changing the value of the Global Tokens? You
should be doing it via Edit-> Project Properties -> Global Token Manager

---

**Comment by CF-Terence** [comment]
Yes, you should be able to see the same settings.

**Comment by foneworkshop** [comment]
Ok when I enter them in G/D (properties,global token) I leave the username and password blank. When I go to edit them manually after upload the username and password are "xbmc"   seems to default to this for some reason?

**Comment by foneworkshop** [comment]
Hi Terence,

Just had a bit of time to check.

If I set Global token to "blank" username and password and upload, when I
open settings it shows "xbmc" in username and password. Not a problem I don
t think, I can just set these to be on in XBMC

Cheers

Ian

-------Original Message-------

From: CF-Terence

Date: 11/07/11 13:25:47

To: foneworkshop

Subject: Re: [XBMC] Global Token (#8)

Yes, you should be able to see the same settings.

---

**Comment by jarrodbell** [comment]
This is a bug in lines 731 and 732 of the XBMCGUIapp.js. If the username or password is blank, it will default to xbmc for both. This should instead allow for blank username and password. So just remove the  || "xbmc"; from the end of those lines.
